version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: echo "testing"
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: echo "building"
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - build
