version: 2
jobs:
  test1:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: echo "testing"
  build:
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - run: echo "building"
workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test
